DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USER_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AUTHORIZED BOOLEAN DEFAULT FALSE
);

INSERT INTO USERS (USER_ID, AUTHORIZED) VALUES ('59785640', TRUE);
INSERT INTO USERS (USER_ID, AUTHORIZED) VALUES ('61614795', TRUE);