DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AUTHORIZED BOOLEAN DEFAULT FALSE NOT NULL,
    RATE_LIMIT_TIMESTAMP VARCHAR(256) NOT NULL DEFAULT '0'
);

CREATE INDEX IF NOT EXISTS IDX_USER_ID ON USERS(USER_ID);

